import React,{useEffect,useState}from'react';
import{createRoot}from'react-dom/client';
import{ArrowLeft,ArrowRight,BookOpen,Check,ChevronRight,Heart,Home,Menu,ShieldAlert,Sparkles,X}from'lucide-react';
import'./style.css';

const chapters=[
 {k:'comece',n:'01',eyebrow:'Antes da primeira tigela',title:'Comece com contexto, não com pressa',lead:'Alimentação natural é uma rotina planejada para o seu cão. Não é oferecer sobras nem copiar uma combinação da internet.',body:[['O que ela é','Comida de verdade preparada com higiene, variedade e uma estratégia individual.'],['O que ela não é','Improviso, tempero humano ou uma receita universal para todos os cães.'],['O ponto de partida','Conhecer idade, peso, rotina, histórico digestivo e condições de saúde.']],note:'Uma refeição “bonita” não é necessariamente completa. O equilíbrio nutricional depende de formulação adequada.'},
 {k:'avaliar',n:'02',eyebrow:'Perfil do seu cão',title:'O que observar antes de mudar',lead:'A mesma escolha pode funcionar para um cão adulto saudável e ser inadequada para outro.',checks:['Idade e fase de vida','Peso e condição corporal','Nível de atividade','Alergias ou sensibilidades','Doenças e medicamentos','Histórico de vômitos ou diarreia'],alert:'Filhotes, gestantes, lactantes, idosos frágeis e cães com doenças renais, hepáticas, cardíacas ou pancreáticas precisam de orientação veterinária antes da mudança.'},
 {k:'componentes',n:'03',eyebrow:'Conheça os componentes',title:'Cada grupo cumpre uma função',lead:'Entender os ingredientes ajuda; saber equilibrá-los é o que protege a saúde no longo prazo.',groups:[['Proteínas','Frango, peru, peixe e cortes bovinos adequados.'],['Vísceras','Podem fornecer nutrientes importantes, em quantidades planejadas.'],['Vegetais','Abóbora, abobrinha, chuchu e cenoura trazem variedade.'],['Fontes energéticas','Arroz, mandioca, inhame e batata-doce podem fazer parte da estratégia.'],['Minerais e vitaminas','Não devem ser improvisados: a dieta precisa cobrir exigências nutricionais.']]},
 {k:'base',n:'04',eyebrow:'A lógica da tigela',title:'Simples para começar. Completa para continuar.',lead:'No início, poucos ingredientes facilitam a observação. Para uso diário, a receita deve ser nutricionalmente balanceada.',formula:['Proteína planejada','Vegetais adequados','Fonte energética quando indicada','Fonte correta de cálcio e micronutrientes'],note:'Não use esta lista como proporção. Quantidades e suplementação mudam conforme o animal e devem seguir uma formulação profissional.'},
 {k:'transicao',n:'05',eyebrow:'Mudança gradual',title:'Uma transição mais leve',lead:'Cães sensíveis podem precisar de mais tempo. Use o calendário como referência, não como obrigação.',steps:[['Dias 1 e 2','25% da nova alimentação'],['Dias 3 e 4','50% da nova alimentação'],['Dias 5 e 6','75% da nova alimentação'],['A partir do dia 7','100%, apenas se houver boa adaptação']],note:'Fezes muito moles, vômitos, coceira ou queda de apetite pedem pausa e avaliação.'},
 {k:'observar',n:'06',eyebrow:'Leia os sinais',title:'Como saber se está indo bem',lead:'A resposta do seu cão vale mais do que seguir um cronograma rígido.',good:['Apetite estável','Fezes bem formadas','Energia habitual','Pele e pelagem estáveis','Peso adequado'],bad:['Vômitos recorrentes','Diarreia persistente','Coceira intensa','Apatia ou dor','Perda de peso sem explicação']},
 {k:'higiene',n:'07',eyebrow:'Segurança na rotina',title:'Prepare, porcione e armazene',lead:'Organização reduz desperdício e risco de contaminação.',checks:['Higienize mãos, bancada, potes e utensílios','Separe porções antes de armazenar','Identifique recipientes com data','Descongele dentro da geladeira','Evite deixar alimento pronto em temperatura ambiente','Descarte em caso de cheiro, cor ou aspecto duvidoso']},
 {k:'evite',n:'08',eyebrow:'Erros comuns',title:'O que não fazer no começo',lead:'A maior parte dos problemas nasce da pressa ou da falsa sensação de simplicidade.',cards:['Trocar toda a alimentação de uma vez','Usar sobras da família','Temperar como comida humana','Repetir uma mistura incompleta por meses','Ignorar mudanças no peso e nas fezes','Suplementar por conta própria']},
 {k:'duvidas',n:'09',eyebrow:'Perguntas frequentes',title:'Dúvidas que quase todo tutor tem',faqs:[['Posso misturar com a ração?','Durante a transição, a mistura pode acontecer. Observe a tolerância e siga a estratégia definida para o cão.'],['Posso colocar sal e temperos?','Evite cebola, alho e temperos prontos. O preparo do cão deve ser separado da comida da família.'],['Cru ou cozido?','As abordagens exigem cuidados diferentes. Para iniciantes, o cozido tende a ser mais simples; decida com orientação.'],['Precisa de suplemento?','Muitas formulações precisam de fontes específicas de minerais e vitaminas. Não escolha produtos ou doses por conta própria.'],['Posso cozinhar para vários dias?','Sim, com porcionamento, refrigeração e congelamento adequados.']]},
 {k:'plano',n:'10',eyebrow:'Seu plano de início',title:'A primeira semana em quatro movimentos',lead:'O objetivo não é perfeição. É criar uma rotina observável e segura.',plan:[['1','Mapeie','Anote peso, rotina, saúde e alimentação atual.'],['2','Planeje','Defina a estratégia com um médico-veterinário ou zootecnista habilitado.'],['3','Organize','Compre, prepare e porcione sem improvisar.'],['4','Observe','Registre apetite, fezes, energia, pele e peso.']]},
 {k:'fim',n:'11',eyebrow:'Para levar com você',title:'Carinho também é planejamento',lead:'Comida de verdade pode trazer variedade e prazer à rotina. O cuidado está em respeitar o organismo e as necessidades únicas do seu cão.',final:true}
];

function App(){const[i,setI]=useState(0),[open,setOpen]=useState(false);const c=chapters[i];useEffect(()=>{window.scrollTo(0,0)},[i]);useEffect(()=>{const h=e=>{if(e.key==='ArrowRight'&&i<chapters.length-1)setI(i+1);if(e.key==='ArrowLeft'&&i>0)setI(i-1)};addEventListener('keydown',h);return()=>removeEventListener('keydown',h)},[i]);return <main className="shell">
 <aside className={open?'side open':'side'}><div className="brand"><span className="brandMark"><Heart size={20}/></span><div><b>Comida de Verdade</b><small>guia para tutores</small></div><button className="close" onClick={()=>setOpen(false)} aria-label="Fechar menu"><X/></button></div><nav>{chapters.map((x,j)=><button key={x.k} className={j===i?'active':''} onClick={()=>{setI(j);setOpen(false)}}><span>{x.n}</span>{x.title}<ChevronRight/></button>)}</nav><div className="sideNote"><ShieldAlert/><p><b>Conteúdo educativo</b><br/>Não substitui avaliação e formulação individual.</p></div></aside>
 <section className="reader"><header><button className="menu" onClick={()=>setOpen(true)} aria-label="Abrir capítulos"><Menu/></button><div className="progress"><span style={{width:`${(i+1)/chapters.length*100}%`}}/></div><small>{String(i+1).padStart(2,'0')} / {chapters.length}</small></header>
 {i===0?<Cover onStart={()=>setI(1)}/>:<Page c={c}/>}<footer><button disabled={i===0} onClick={()=>setI(Math.max(0,i-1))}><ArrowLeft/>Anterior</button><button className="home" onClick={()=>setI(0)} aria-label="Voltar à capa"><Home/></button><button disabled={i===chapters.length-1} onClick={()=>setI(Math.min(chapters.length-1,i+1))}>Próximo<ArrowRight/></button></footer></section>
 </main>}

function Cover({onStart}){return <article className="cover"><div className="coverPhoto"><img src="/dog-cover.jpg" alt="Cão diante de uma tigela de comida preparada em casa"/></div><div className="coverCopy"><span className="pill"><Sparkles/> Guia essencial</span><h1>Comida<br/><em>de Verdade</em><br/>para Cães</h1><p>Um começo consciente na alimentação natural canina — com organização, segurança e expectativas reais.</p><button onClick={onStart}>Começar leitura <ArrowRight/></button><div className="trust"><ShieldAlert/><span>Orientação educativa<br/><b>sem promessas milagrosas</b></span></div></div></article>}

function Page({c}){return <article className={`page ${c.final?'final':''}`}><div className="pageHead"><span>{c.n}</span><div><small>{c.eyebrow}</small><h2>{c.title}</h2>{c.lead&&<p>{c.lead}</p>}</div></div>
 {c.body&&<div className="featureGrid">{c.body.map(([a,b],j)=><section key={a}><i>0{j+1}</i><h3>{a}</h3><p>{b}</p></section>)}</div>}
 {c.checks&&<div className="checks">{c.checks.map(x=><div key={x}><Check/>{x}</div>)}</div>}
 {c.groups&&<div className="groups">{c.groups.map(([a,b],j)=><section key={a}><span>{j+1}</span><div><h3>{a}</h3><p>{b}</p></div></section>)}</div>}
 {c.formula&&<div className="formula">{c.formula.map((x,j)=><div key={x}><span>{j+1}</span>{x}</div>)}</div>}
 {c.steps&&<div className="timeline">{c.steps.map(([a,b],j)=><section key={a}><i style={{'--w':`${25*(j+1)}%`}}/><small>{a}</small><b>{b}</b></section>)}</div>}
 {(c.good||c.bad)&&<div className="compare"><section><h3>Sinais positivos</h3>{c.good.map(x=><p key={x}><Check/>{x}</p>)}</section><section className="warning"><h3>Sinais de alerta</h3>{c.bad.map(x=><p key={x}><ShieldAlert/>{x}</p>)}</section></div>}
 {c.cards&&<div className="cardGrid">{c.cards.map((x,j)=><section key={x}><b>{String(j+1).padStart(2,'0')}</b><p>{x}</p></section>)}</div>}
 {c.faqs&&<div className="faqs">{c.faqs.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div>}
 {c.plan&&<div className="plan">{c.plan.map(([n,a,b])=><section key={n}><b>{n}</b><div><h3>{a}</h3><p>{b}</p></div></section>)}</div>}
 {c.alert&&<aside className="alert"><ShieldAlert/><p>{c.alert}</p></aside>}{c.note&&<aside className="note"><BookOpen/><p>{c.note}</p></aside>}
 {c.final&&<div className="finalCard"><Heart/><p>Comece simples, observe com atenção e procure orientação sempre que houver dúvida.</p><span>Seu cão não precisa de uma tendência.<br/><b>Precisa de uma rotina feita para ele.</b></span></div>}
 </article>}
createRoot(document.getElementById('root')).render(<App/>);
